MainApp/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views
app_name = 'MainApp'

urlpatterns = [

    path('',views.index, name='index'),
    path("topics", views.topics, name="topics"),
    path('topics/<int:topic_id>/',views.topic,name='topic')

]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('users/', include('users.urls')),
]

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        return f"{self.text[:50]}..."

MainApp/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}

MainApp/views.py
from django.shortcuts import render, redirect
from .forms import EntryForm, TopicForm
from .models import Topic, Entry
from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.
def index(request):
    return render(request, "MainApp/index.html")


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")

    context = {"topics": topics}

    return render(request, "MainApp/topics.html", context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.all()

    context = {"topic": topic, 'entries': entries}

    return render(request, "MainApp/topic.html", context)
@login_required    
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return redirect('MainApp:topics')
    context = {'form': form}
    return render(request, 'MainApp/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.topic = topic
            new_entry.save()
            return redirect('MainApp:topic',topic_id=topic_id)
    context = {'form': form,'topic':topic}
    return render(request, 'MainApp/new_entry.html', context)

@login_required
def edit_entry(request,entry_id):
    """edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('MainApp:topic',topic_id=topic.id)
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'MainApp/edit_entry.html', context)      

MainApp/templates/mainapp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Learning Log</a>
    <a href="{% url 'MainApp:topics'%}">Topics</a>
</p>

{% block content %}

{% endblock content %}

MainApp/templates/mainapp/index.html
<p>Learning Log</p>

<p>Learning Log helps you keep track of your learning, for any topic
    you're learning about.</p>

MainApp/templates/mainapp/topic.html
{% extends "MainApp/base.html" %}

{% block content %}

<p>Topic: {{ topic }}</p>

<ul>
   {% for e in entries %}
   <li>
       <p>{{e.text}}</p>
       <p>{{e.date_added}}</p>
   </li>
   {% empty %}
   <li> There are no entries for this topic yet. </li>
   {% endfor %}
</ul>

{% end block content%}

MainApp/templates/mainapp/topics.html
{% extends "MainApp/base.html" %}

{% block content %}

<p>Topics</p>

<ul>
    {% for t in topics %}

    <li>
        <a href="{% url 'MainApp:topic' t.id %}">{{ t }}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% end block content%}